name: Code Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Run checks
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Ruff
      run: pip install ruff

    - name: Install uv
      run: pip install uv
      
    - name: Run check.sh script
      run: |
        chmod +x ./check.sh
        ./check.sh